theme: jekyll-theme-minimal
title: qube
description: A virtual office that enables you to work remotely. See who's chatting with coworkers, out of the office, or stepped out for lunch.
logo:  https://raw.githubusercontent.com/seeq12/qube/master/pages/qube.png
baseurl: /qube
